#!/bin/sh
#
# Copyright 2011 Brian de Alwis
# Licensed under the Eclipse Public License v1.0
# http://www.eclipse.org/org/documents/epl-v10.php
#
P2HOME=${P2HOME:?P2HOME is not set}
ECLIPSEHOME=${ECLIPSEHOME:?ECLIPSEHOME is not set}
. $P2HOME/tools.sh || exit -1

flavour="tooling"
execloc=""

usage()
{
    eval 1>&2
    echo "Invoke the p2 director to list the IUs available in a repository."
    echo "use: $progname [-v] repo-loc"
    echo
    echo "  -v  be more verbose"
    echo
    echo "  repo-loc	the location of th p2 artifact and metadata repo"
    exit 1
}

while getopts v c; do
    case $c in
    v)  verbose=true;;
    \?)	usage;;
    esac
done
shift `expr $OPTIND - 1`

if [ $# -lt 1 ]; then
    usage
fi

repoLoc=$(rewriteRepoLoc "$1")
shift 1

runEclipse -application org.eclipse.equinox.p2.director \
    -repository "$repoLoc" \
    -list $(echo $* | sed 's/[[:space:]][[:space:]]*/,/g')
