#!/bin/sh
#
# Copyright 2011 Brian de Alwis
# Licensed under the Eclipse Public License v1.0
# http://www.eclipse.org/org/documents/epl-v10.php
#
P2HOME=${P2HOME:?P2HOME is not set}
ECLIPSEHOME=${ECLIPSEHOME:?ECLIPSEHOME is not set}
. $P2HOME/tools.sh || exit -1

usage()
{
    eval 1>&2
    echo "Invoke the p2 repo2runnable application."
    echo
    echo "use: $progname [-v] dest-location source-location ..."
    exit 1
}

while getopts v c; do
    case $c in
    v)  verbose="true";;
    \?)	usage;;
    esac
done
shift `expr $OPTIND - 1`

if [ $# -lt 2 ]; then
    usage
fi

destLoc="$1"
shift

if [ -d "$destLoc" ]; then
    error "$destLoc: destination location already exists"
fi

runEclipse -application org.eclipse.equinox.p2.repository.repo2runnable \
    $(for source in "$@"; do \
	echo "-source $(rewriteRepoLoc "$source")"; \
    done) \
    -destination $(absolute "$destLoc")

